package js.node;

import js.lib.Error;

/**
	Diagnostic report API available via `process.report`.

	@see https://nodejs.org/api/process.html#processreport
**/
extern class Report {
	/**
		If the reports are written in compact mode.
	**/
	var compact:Bool;

	/**
		The directory in which the reports are written.
	**/
	var directory:String;

	/**
		The file in which the reports are written.
	**/
	var filename:String;

	/**
		Returns the diagnostic report as an object. Optionally from an error object.
	**/
	function getReport(?err:Error):Dynamic;

	/**
		When the diagnostic report was generated in case of fatal errors.
	**/
	var reportOnFatalError:Bool;

	/**
		If the diagnostic report was generated by receiving a signal.
	**/
	var reportOnSignal:Bool;

	/**
		When the diagnostic report was generated in case of a uncaught exception.
	**/
	var reportOnUncaughtException:Bool;

	/**
		If `true`, the environment variables are excluded from the report.
		Default: `false`.

		@see https://nodejs.org/api/process.html#processreportexcludeenv
	**/
	var excludeEnv:Bool;

	/**
		The signal that triggered the diagnostic report.
	**/
	var signal:String;

	/**
		Writes a diagnostic report to a file.
	**/
	function writeReport(?filename:String, ?err:Error):String;
}
