/*
 * Copyright (C)2014-2026 Haxe Foundation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

package js.node;

import js.node.trace_events.Tracing;

/**
	The `node:trace_events` module centralizes tracing information generated by
	V8, Node.js core, and userspace code.

	Tracing can also be enabled with the `--trace-event-categories` command-line
	flag. Features from this module are not available in Worker threads.

	Stability: 1 - Experimental.

	@see https://nodejs.org/docs/latest-v24.x/api/tracing.html
**/
@:jsRequire("node:trace_events")
extern class TraceEvents {
	/**
		Creates and returns a `Tracing` object for the given set of `categories`.

		@see https://nodejs.org/docs/latest-v24.x/api/tracing.html#trace_eventscreatetracingoptions
	**/
	static function createTracing(options:CreateTracingOptions):Tracing;

	/**
		Returns a comma-separated list of all currently-enabled trace event categories.
		The set is the union of all enabled `Tracing` objects and categories enabled
		via `--trace-event-categories`. Returns `null`/`undefined` when none are enabled.

		@see https://nodejs.org/docs/latest-v24.x/api/tracing.html#trace_eventsgetenabledcategories
	**/
	static function getEnabledCategories():Null<String>;
}

/**
	Options for `TraceEvents.createTracing`.
**/
typedef CreateTracingOptions = {
	/**
		An array of trace category names. Values are coerced to a string when possible;
		an error is thrown if a value cannot be coerced.
	**/
	var categories:Array<String>;
}
