/*
 * Copyright (C)2014-2026 Haxe Foundation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

package js.node.http2;

/**
	Constants exposed by the `http2` module (`http2.constants`).

	@see https://nodejs.org/api/http2.html#http2constants
**/
typedef Http2Constants = {
	var DEFAULT_SETTINGS_ENABLE_CONNECT_PROTOCOL:Int;
	var DEFAULT_SETTINGS_ENABLE_PUSH:Int;
	var DEFAULT_SETTINGS_HEADER_TABLE_SIZE:Int;
	var DEFAULT_SETTINGS_INITIAL_WINDOW_SIZE:Int;
	var DEFAULT_SETTINGS_MAX_CONCURRENT_STREAMS:Int;
	var DEFAULT_SETTINGS_MAX_FRAME_SIZE:Int;
	var DEFAULT_SETTINGS_MAX_HEADER_LIST_SIZE:Int;
	var HTTP2_HEADER_ACCEPT:String;
	var HTTP2_HEADER_ACCEPT_CHARSET:String;
	var HTTP2_HEADER_ACCEPT_ENCODING:String;
	var HTTP2_HEADER_ACCEPT_LANGUAGE:String;
	var HTTP2_HEADER_ACCEPT_RANGES:String;
	var HTTP2_HEADER_ACCESS_CONTROL_ALLOW_CREDENTIALS:String;
	var HTTP2_HEADER_ACCESS_CONTROL_ALLOW_HEADERS:String;
	var HTTP2_HEADER_ACCESS_CONTROL_ALLOW_METHODS:String;
	var HTTP2_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN:String;
	var HTTP2_HEADER_ACCESS_CONTROL_EXPOSE_HEADERS:String;
	var HTTP2_HEADER_ACCESS_CONTROL_MAX_AGE:String;
	var HTTP2_HEADER_ACCESS_CONTROL_REQUEST_HEADERS:String;
	var HTTP2_HEADER_ACCESS_CONTROL_REQUEST_METHOD:String;
	var HTTP2_HEADER_AGE:String;
	var HTTP2_HEADER_ALLOW:String;
	var HTTP2_HEADER_ALT_SVC:String;
	var HTTP2_HEADER_AUTHORITY:String;
	var HTTP2_HEADER_AUTHORIZATION:String;
	var HTTP2_HEADER_CACHE_CONTROL:String;
	var HTTP2_HEADER_CONNECTION:String;
	var HTTP2_HEADER_CONTENT_DISPOSITION:String;
	var HTTP2_HEADER_CONTENT_ENCODING:String;
	var HTTP2_HEADER_CONTENT_LANGUAGE:String;
	var HTTP2_HEADER_CONTENT_LENGTH:String;
	var HTTP2_HEADER_CONTENT_LOCATION:String;
	var HTTP2_HEADER_CONTENT_MD5:String;
	var HTTP2_HEADER_CONTENT_RANGE:String;
	var HTTP2_HEADER_CONTENT_SECURITY_POLICY:String;
	var HTTP2_HEADER_CONTENT_TYPE:String;
	var HTTP2_HEADER_COOKIE:String;
	var HTTP2_HEADER_DATE:String;
	var HTTP2_HEADER_DNT:String;
	var HTTP2_HEADER_EARLY_DATA:String;
	var HTTP2_HEADER_ETAG:String;
	var HTTP2_HEADER_EXPECT:String;
	var HTTP2_HEADER_EXPECT_CT:String;
	var HTTP2_HEADER_EXPIRES:String;
	var HTTP2_HEADER_FORWARDED:String;
	var HTTP2_HEADER_FROM:String;
	var HTTP2_HEADER_HOST:String;
	var HTTP2_HEADER_HTTP2_SETTINGS:String;
	var HTTP2_HEADER_IF_MATCH:String;
	var HTTP2_HEADER_IF_MODIFIED_SINCE:String;
	var HTTP2_HEADER_IF_NONE_MATCH:String;
	var HTTP2_HEADER_IF_RANGE:String;
	var HTTP2_HEADER_IF_UNMODIFIED_SINCE:String;
	var HTTP2_HEADER_KEEP_ALIVE:String;
	var HTTP2_HEADER_LAST_MODIFIED:String;
	var HTTP2_HEADER_LINK:String;
	var HTTP2_HEADER_LOCATION:String;
	var HTTP2_HEADER_MAX_FORWARDS:String;
	var HTTP2_HEADER_METHOD:String;
	var HTTP2_HEADER_ORIGIN:String;
	var HTTP2_HEADER_PATH:String;
	var HTTP2_HEADER_PREFER:String;
	var HTTP2_HEADER_PRIORITY:String;
	var HTTP2_HEADER_PROTOCOL:String;
	var HTTP2_HEADER_PROXY_AUTHENTICATE:String;
	var HTTP2_HEADER_PROXY_AUTHORIZATION:String;
	var HTTP2_HEADER_PROXY_CONNECTION:String;
	var HTTP2_HEADER_PURPOSE:String;
	var HTTP2_HEADER_RANGE:String;
	var HTTP2_HEADER_REFERER:String;
	var HTTP2_HEADER_REFRESH:String;
	var HTTP2_HEADER_RETRY_AFTER:String;
	var HTTP2_HEADER_SCHEME:String;
	var HTTP2_HEADER_SERVER:String;
	var HTTP2_HEADER_SET_COOKIE:String;
	var HTTP2_HEADER_STATUS:String;
	var HTTP2_HEADER_STRICT_TRANSPORT_SECURITY:String;
	var HTTP2_HEADER_TE:String;
	var HTTP2_HEADER_TIMING_ALLOW_ORIGIN:String;
	var HTTP2_HEADER_TK:String;
	var HTTP2_HEADER_TRAILER:String;
	var HTTP2_HEADER_TRANSFER_ENCODING:String;
	var HTTP2_HEADER_UPGRADE:String;
	var HTTP2_HEADER_UPGRADE_INSECURE_REQUESTS:String;
	var HTTP2_HEADER_USER_AGENT:String;
	var HTTP2_HEADER_VARY:String;
	var HTTP2_HEADER_VIA:String;
	var HTTP2_HEADER_WARNING:String;
	var HTTP2_HEADER_WWW_AUTHENTICATE:String;
	var HTTP2_HEADER_X_CONTENT_TYPE_OPTIONS:String;
	var HTTP2_HEADER_X_FORWARDED_FOR:String;
	var HTTP2_HEADER_X_FRAME_OPTIONS:String;
	var HTTP2_HEADER_X_XSS_PROTECTION:String;
	var HTTP2_METHOD_ACL:String;
	var HTTP2_METHOD_BASELINE_CONTROL:String;
	var HTTP2_METHOD_BIND:String;
	var HTTP2_METHOD_CHECKIN:String;
	var HTTP2_METHOD_CHECKOUT:String;
	var HTTP2_METHOD_CONNECT:String;
	var HTTP2_METHOD_COPY:String;
	var HTTP2_METHOD_DELETE:String;
	var HTTP2_METHOD_GET:String;
	var HTTP2_METHOD_HEAD:String;
	var HTTP2_METHOD_LABEL:String;
	var HTTP2_METHOD_LINK:String;
	var HTTP2_METHOD_LOCK:String;
	var HTTP2_METHOD_MERGE:String;
	var HTTP2_METHOD_MKACTIVITY:String;
	var HTTP2_METHOD_MKCALENDAR:String;
	var HTTP2_METHOD_MKCOL:String;
	var HTTP2_METHOD_MKREDIRECTREF:String;
	var HTTP2_METHOD_MKWORKSPACE:String;
	var HTTP2_METHOD_MOVE:String;
	var HTTP2_METHOD_OPTIONS:String;
	var HTTP2_METHOD_ORDERPATCH:String;
	var HTTP2_METHOD_PATCH:String;
	var HTTP2_METHOD_POST:String;
	var HTTP2_METHOD_PRI:String;
	var HTTP2_METHOD_PROPFIND:String;
	var HTTP2_METHOD_PROPPATCH:String;
	var HTTP2_METHOD_PUT:String;
	var HTTP2_METHOD_REBIND:String;
	var HTTP2_METHOD_REPORT:String;
	var HTTP2_METHOD_SEARCH:String;
	var HTTP2_METHOD_TRACE:String;
	var HTTP2_METHOD_UNBIND:String;
	var HTTP2_METHOD_UNCHECKOUT:String;
	var HTTP2_METHOD_UNLINK:String;
	var HTTP2_METHOD_UNLOCK:String;
	var HTTP2_METHOD_UPDATE:String;
	var HTTP2_METHOD_UPDATEREDIRECTREF:String;
	var HTTP2_METHOD_VERSION_CONTROL:String;
	var HTTP_STATUS_ACCEPTED:Int;
	var HTTP_STATUS_ALREADY_REPORTED:Int;
	var HTTP_STATUS_BAD_GATEWAY:Int;
	var HTTP_STATUS_BAD_REQUEST:Int;
	var HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED:Int;
	var HTTP_STATUS_CONFLICT:Int;
	var HTTP_STATUS_CONTINUE:Int;
	var HTTP_STATUS_CREATED:Int;
	var HTTP_STATUS_EARLY_HINTS:Int;
	var HTTP_STATUS_EXPECTATION_FAILED:Int;
	var HTTP_STATUS_FAILED_DEPENDENCY:Int;
	var HTTP_STATUS_FORBIDDEN:Int;
	var HTTP_STATUS_FOUND:Int;
	var HTTP_STATUS_GATEWAY_TIMEOUT:Int;
	var HTTP_STATUS_GONE:Int;
	var HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED:Int;
	var HTTP_STATUS_IM_USED:Int;
	var HTTP_STATUS_INSUFFICIENT_STORAGE:Int;
	var HTTP_STATUS_INTERNAL_SERVER_ERROR:Int;
	var HTTP_STATUS_LENGTH_REQUIRED:Int;
	var HTTP_STATUS_LOCKED:Int;
	var HTTP_STATUS_LOOP_DETECTED:Int;
	var HTTP_STATUS_METHOD_NOT_ALLOWED:Int;
	var HTTP_STATUS_MISDIRECTED_REQUEST:Int;
	var HTTP_STATUS_MOVED_PERMANENTLY:Int;
	var HTTP_STATUS_MULTIPLE_CHOICES:Int;
	var HTTP_STATUS_MULTI_STATUS:Int;
	var HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED:Int;
	var HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION:Int;
	var HTTP_STATUS_NOT_ACCEPTABLE:Int;
	var HTTP_STATUS_NOT_EXTENDED:Int;
	var HTTP_STATUS_NOT_FOUND:Int;
	var HTTP_STATUS_NOT_IMPLEMENTED:Int;
	var HTTP_STATUS_NOT_MODIFIED:Int;
	var HTTP_STATUS_NO_CONTENT:Int;
	var HTTP_STATUS_OK:Int;
	var HTTP_STATUS_PARTIAL_CONTENT:Int;
	var HTTP_STATUS_PAYLOAD_TOO_LARGE:Int;
	var HTTP_STATUS_PAYMENT_REQUIRED:Int;
	var HTTP_STATUS_PERMANENT_REDIRECT:Int;
	var HTTP_STATUS_PRECONDITION_FAILED:Int;
	var HTTP_STATUS_PRECONDITION_REQUIRED:Int;
	var HTTP_STATUS_PROCESSING:Int;
	var HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED:Int;
	var HTTP_STATUS_RANGE_NOT_SATISFIABLE:Int;
	var HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE:Int;
	var HTTP_STATUS_REQUEST_TIMEOUT:Int;
	var HTTP_STATUS_RESET_CONTENT:Int;
	var HTTP_STATUS_SEE_OTHER:Int;
	var HTTP_STATUS_SERVICE_UNAVAILABLE:Int;
	var HTTP_STATUS_SWITCHING_PROTOCOLS:Int;
	var HTTP_STATUS_TEAPOT:Int;
	var HTTP_STATUS_TEMPORARY_REDIRECT:Int;
	var HTTP_STATUS_TOO_EARLY:Int;
	var HTTP_STATUS_TOO_MANY_REQUESTS:Int;
	var HTTP_STATUS_UNAUTHORIZED:Int;
	var HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS:Int;
	var HTTP_STATUS_UNPROCESSABLE_ENTITY:Int;
	var HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE:Int;
	var HTTP_STATUS_UPGRADE_REQUIRED:Int;
	var HTTP_STATUS_URI_TOO_LONG:Int;
	var HTTP_STATUS_USE_PROXY:Int;
	var HTTP_STATUS_VARIANT_ALSO_NEGOTIATES:Int;
	var MAX_INITIAL_WINDOW_SIZE:Int;
	var MAX_MAX_FRAME_SIZE:Int;
	var MIN_MAX_FRAME_SIZE:Int;
	var NGHTTP2_CANCEL:Int;
	var NGHTTP2_COMPRESSION_ERROR:Int;
	var NGHTTP2_CONNECT_ERROR:Int;
	var NGHTTP2_DEFAULT_WEIGHT:Int;
	var NGHTTP2_ENHANCE_YOUR_CALM:Int;
	var NGHTTP2_ERR_FRAME_SIZE_ERROR:Int;
	var NGHTTP2_FLAG_ACK:Int;
	var NGHTTP2_FLAG_END_HEADERS:Int;
	var NGHTTP2_FLAG_END_STREAM:Int;
	var NGHTTP2_FLAG_NONE:Int;
	var NGHTTP2_FLAG_PADDED:Int;
	var NGHTTP2_FLAG_PRIORITY:Int;
	var NGHTTP2_FLOW_CONTROL_ERROR:Int;
	var NGHTTP2_FRAME_SIZE_ERROR:Int;
	var NGHTTP2_HTTP_1_1_REQUIRED:Int;
	var NGHTTP2_INADEQUATE_SECURITY:Int;
	var NGHTTP2_INTERNAL_ERROR:Int;
	var NGHTTP2_NO_ERROR:Int;
	var NGHTTP2_PROTOCOL_ERROR:Int;
	var NGHTTP2_REFUSED_STREAM:Int;
	var NGHTTP2_SESSION_CLIENT:Int;
	var NGHTTP2_SESSION_SERVER:Int;
	var NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL:Int;
	var NGHTTP2_SETTINGS_ENABLE_PUSH:Int;
	var NGHTTP2_SETTINGS_HEADER_TABLE_SIZE:Int;
	var NGHTTP2_SETTINGS_INITIAL_WINDOW_SIZE:Int;
	var NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS:Int;
	var NGHTTP2_SETTINGS_MAX_FRAME_SIZE:Int;
	var NGHTTP2_SETTINGS_MAX_HEADER_LIST_SIZE:Int;
	var NGHTTP2_SETTINGS_TIMEOUT:Int;
	var NGHTTP2_STREAM_CLOSED:Int;
	var NGHTTP2_STREAM_STATE_CLOSED:Int;
	var NGHTTP2_STREAM_STATE_HALF_CLOSED_LOCAL:Int;
	var NGHTTP2_STREAM_STATE_HALF_CLOSED_REMOTE:Int;
	var NGHTTP2_STREAM_STATE_IDLE:Int;
	var NGHTTP2_STREAM_STATE_OPEN:Int;
	var NGHTTP2_STREAM_STATE_RESERVED_LOCAL:Int;
	var NGHTTP2_STREAM_STATE_RESERVED_REMOTE:Int;
	var PADDING_STRATEGY_ALIGNED:Int;
	var PADDING_STRATEGY_CALLBACK:Int;
	var PADDING_STRATEGY_MAX:Int;
	var PADDING_STRATEGY_NONE:Int;
}
